wood.png:
    derived-from: williamson-roguelike-items, daneeklu-farming-tilesets
    attribution:
        Recolored Williamson's wood icon using colors from Daneeklu's.

stones.png:
    derived-from: williamson-roguelike-items, lpc-base-tiles
    attribution:
        Recolored Williamson's rock and ore tiles to match LPC rocks.

crystal.png:
    author: Stuart Pernsteiner
    derived-from: gervais-roguelike-tiles
    attribution: Based on the blue crystal clusten in dg_misc32.gif

equip_hat_icon.png: &witch-hat
    attribution: Based on the witch hat sprite sheet
equip_hat_icon_remove.png: *witch-hat

party-hat-icon.*:
    title: Party Hat
    author: Stuart Pernsteiner

santa-hat-icon.*:
    title: Santa Hat
    author: Stuart Pernsteiner

key.png:
    derived-from: williamson-roguelike-items

candle.png:
    title: Candle Icon
    author: Stuart Pernsteiner

crops.png:
    derived-from: daneeklu-farming-tilesets

gervais_roguelike/*.png: &gervais-roguelike
    derived-from: gervais-roguelike-tiles

blueprint.png:
    derived-from: williamson-roguelike-items
    attribution: Page/note icon, recolored to look like a blueprint
